package com.niit.util;

import net.coobird.thumbnailator.Thumbnails;
import org.springframework.stereotype.Component;

import java.io.File;
import java.io.IOException;

@Component
public class ImageUtil {
    /**
     * 压缩图片到指定尺寸
     *
     * @param inputPath
     * @param outputPath
     */
    public void condenseImage(String inputPath, String outputPath) {
        String prefix = outputPath.substring(0, outputPath.lastIndexOf("."));
//        System.out.println("prefix1 " + prefix);
        prefix += "_autoGenerated";
//        System.out.println("prefix2 " + prefix);
        String suffix = outputPath.substring(outputPath.lastIndexOf(".") + 1);
        System.out.println("suffix " + suffix);
        String outputPath2 = prefix + "." + suffix;
//        System.out.println(outputPath2);
        double weight = 320;
        double height = weight / (16.0 / 25.0) * (9.0 / 25.0);
        try {
            Thumbnails.of(inputPath).forceSize((int) weight, (int) height).toFile(outputPath2);
            //增加过渡文件，防止压缩失败时输出的图片受损
            File inputFile = new File(inputPath);
            inputFile.delete();
            File autoGeneratedFile = new File(outputPath2);
            File newFile = new File(outputPath);
            autoGeneratedFile.renameTo(newFile);
        } catch (IOException e) {
            System.out.println("压缩视频封面失败");
            e.printStackTrace();
        }
    }

    /**
     * 压缩用户头像
     *
     * @param inputPath
     * @param outputPath
     */
    public void condenseHeadshot(String inputPath, String outputPath) {
        String prefix = outputPath.substring(0, outputPath.lastIndexOf("."));
        prefix += "_autoGenerated";
        String suffix = outputPath.substring(outputPath.lastIndexOf(".") + 1);
        String outputPath2 = prefix + "." + suffix;
        double weight = 100;
        double height = 100;
        try {
            Thumbnails.of(inputPath).forceSize((int) weight, (int) height).toFile(outputPath2);
            //增加过渡文件，防止压缩失败时输出的图片受损
            File inputFile = new File(inputPath);
            inputFile.delete();
            File autoGeneratedFile = new File(outputPath2);
            File newFile = new File(outputPath);
            autoGeneratedFile.renameTo(newFile);
        } catch (IOException e) {
            System.out.println("压缩用户头像失败");
            e.printStackTrace();
        }
    }
}
